#!/usr/bin/env python3
"""Turn Rasa's evaluation output into a report-ready Markdown summary.

`rasa test` writes JSON and PNG files that are awkward to quote directly. This
reads whatever is present under docs/metrics/ and writes RESULTS.md: per-intent
precision/recall/F1, the entity-role breakdown, dialogue accuracy, and the
intents most often confused with each other.

    python scripts/summarise_metrics.py --metrics docs/metrics
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

EXCLUDED_KEYS = {"accuracy", "macro avg", "weighted avg", "micro avg"}


def load(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def classification_table(report: dict[str, Any], label: str, limit: int | None = None) -> list[str]:
    rows = [
        (name, stats)
        for name, stats in report.items()
        if name not in EXCLUDED_KEYS and isinstance(stats, dict) and "f1-score" in stats
    ]
    rows.sort(key=lambda item: item[1]["f1-score"])
    if limit:
        rows = rows[:limit]

    lines = [f"| {label} | Precision | Recall | F1 | Support |", "|---|---|---|---|---|"]
    for name, stats in rows:
        lines.append(
            f"| `{name}` | {stats['precision']:.3f} | {stats['recall']:.3f} "
            f"| {stats['f1-score']:.3f} | {int(stats['support'])} |"
        )
    return lines


def headline(report: dict[str, Any]) -> list[str]:
    lines = []
    if "accuracy" in report:
        lines.append(f"- **Accuracy:** {report['accuracy']:.3f}")
    for key, pretty in (("weighted avg", "Weighted average"), ("macro avg", "Macro average")):
        if key in report:
            stats = report[key]
            lines.append(
                f"- **{pretty}:** precision {stats['precision']:.3f}, "
                f"recall {stats['recall']:.3f}, F1 {stats['f1-score']:.3f}"
            )
    return lines


def confusions(errors: list[dict[str, Any]], limit: int = 12) -> list[str]:
    counts: dict[tuple[str, str], int] = {}
    for error in errors:
        pair = (str(error.get("intent", "?")), str(error.get("intent_prediction", {}).get("name", "?")))
        counts[pair] = counts.get(pair, 0) + 1

    if not counts:
        return ["No misclassifications recorded."]

    lines = ["| True intent | Predicted as | Count |", "|---|---|---|"]
    for (true, predicted), count in sorted(counts.items(), key=lambda kv: -kv[1])[:limit]:
        lines.append(f"| `{true}` | `{predicted}` | {count} |")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--metrics", default="docs/metrics")
    args = parser.parse_args()

    root = Path(args.metrics)
    out: list[str] = [
        "# Evaluation results",
        "",
        "Generated by `scripts/summarise_metrics.py` from the raw `rasa test` output in",
        "this directory. Every figure below comes from a run against the committed model;",
        "nothing here is hand-entered.",
        "",
    ]

    # --- NLU -------------------------------------------------------------
    for folder, title, note in (
        ("nlu-cv", "NLU — 5-fold cross-validation", "Every example is held out exactly once. This is the honest number."),
        ("nlu", "NLU — 80/20 holdout", "Faster, and optimistic relative to cross-validation."),
    ):
        intent_report = load(root / folder / "intent_report.json")
        if not intent_report:
            continue

        out += [f"## {title}", "", note, ""] + headline(intent_report) + [""]
        out += ["### Per-intent scores (weakest first)", ""] + classification_table(intent_report, "Intent") + [""]

        errors = load(root / folder / "intent_errors.json")
        if isinstance(errors, list):
            out += [
                "### Most frequent confusions",
                "",
                f"{len(errors)} misclassified examples in total.",
                "",
            ] + confusions(errors) + [""]

        entity_reports = sorted(root.glob(f"{folder}/*entity_report.json"))
        for entity_path in entity_reports:
            entity_report = load(entity_path)
            if not entity_report:
                continue
            extractor = entity_path.stem.replace("_entity_report", "") or "extractor"
            out += [f"### Entities — {extractor}", ""] + headline(entity_report) + [""]
            out += classification_table(entity_report, "Entity / role") + [""]

        response_report = load(root / folder / "response_selection_report.json")
        if response_report:
            out += ["### Response selection", ""] + headline(response_report) + [""]

    # --- Core ------------------------------------------------------------
    story_report = load(root / "core" / "story_report.json")
    if story_report:
        out += ["## Dialogue management — end-to-end story tests", ""] + headline(story_report) + [""]
        out += ["### Per-action scores (weakest first)", ""] + classification_table(story_report, "Action") + [""]

    failed = (root / "core" / "failed_test_stories.yml")
    if failed.exists():
        body = failed.read_text(encoding="utf-8").strip()
        count = body.count("- story:")
        out += [
            "### Failed stories",
            "",
            f"{count} failing conversation{'s' if count != 1 else ''}."
            + (" See `core/failed_test_stories.yml`." if count else " Every test conversation completed as specified."),
            "",
        ]

    if len(out) <= 6:
        out += ["_No evaluation output found. Run the commands in the README's Testing section first._", ""]

    target = root / "RESULTS.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {target} ({len(out)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
